---
apiVersion: v1
kind: Service
metadata:
  name: am-analytics-dash-service
spec:
  type: NodePort
  selector:
    app: am-analytics-dash
  ports:
  - name: dash
    protocol: TCP
    port: 9643
    targetPort: 9643
