---
apiVersion: v1
kind: Service
metadata:
  name: api-manager-externo-service
spec:
  type: NodePort
  selector:
    app: api-manager
  ports:
  - name: apim1
    protocol: TCP
    port: 9443
    targetPort: 9443
  - name: apim2
    protocol: TCP
    port: 8280
    targetPort: 8280
  - name: apim3
    protocol: TCP
    port: 8243
    targetPort: 8243

---
apiVersion: v1
kind: Service
metadata:
  name: api-manager-interno-service
spec:
  selector:
    app: api-manager
  ports: 
  - name: apim4
    protocol: TCP
    port: 9611
    targetPort: 9611
  - name: apim5
    protocol: TCP
    port: 9711
    targetPort: 9711
  - name: apim6
    protocol: TCP
    port: 5672
    targetPort: 5672
