---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-manager-executionplans
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200M
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-manager-synapse-configs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200M
