---
apiVersion: v1
kind: Service
metadata:
  name: am-analytics-worker-service
spec:
  selector:
    app: am-analytics-worker
  ports:
  - name: worker1
    protocol: TCP
    port: 9092
    targetPort: 9092
  - name: worker2
    protocol: TCP
    port: 9445
    targetPort: 9445
  - name: worker3
    protocol: TCP
    port: 7613
    targetPort: 7613
  - name: worker4
    protocol: TCP
    port: 7713
    targetPort: 7713
